// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB4yPhRR2z6NAmjZ5wF0_7jgKTfrodgZ4',
    appId: '1:1043118754254:web:9cf59a89173fa0e714c39f',
    messagingSenderId: '1043118754254',
    projectId: 'joing-app',
    authDomain: 'joing-app.firebaseapp.com',
    storageBucket: 'joing-app.appspot.com',
    measurementId: 'G-5Y2LRW02MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1NbM76HxUUbORS9qQTD97ILcbfP_kFAY',
    appId: '1:1043118754254:android:8e93c0abe487881814c39f',
    messagingSenderId: '1043118754254',
    projectId: 'joing-app',
    storageBucket: 'joing-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvaRembUD6rjcQWB9HeifTAOGjJ8c2Elk',
    appId: '1:1043118754254:ios:876f6dd16da8ff8f14c39f',
    messagingSenderId: '1043118754254',
    projectId: 'joing-app',
    storageBucket: 'joing-app.appspot.com',
    iosClientId: '1043118754254-cfhfsnj9a850j6f2q2hcvd15g3tfja1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.joingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvaRembUD6rjcQWB9HeifTAOGjJ8c2Elk',
    appId: '1:1043118754254:ios:876f6dd16da8ff8f14c39f',
    messagingSenderId: '1043118754254',
    projectId: 'joing-app',
    storageBucket: 'joing-app.appspot.com',
    iosClientId: '1043118754254-cfhfsnj9a850j6f2q2hcvd15g3tfja1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.joingApp',
  );
}
